name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y build-essential cmake
    - name: Configure the project
      run: cmake -S . -B build
    - name: Build the project
      run: cmake --build build