name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    - name: Install GCC 9
      run: |
        sudo apt-get install -y gcc-9 g++-9
    - name: Set up GCC 9
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 \
                                --slave /usr/bin/g++ g++ /usr/bin/g++-9
    - name: Check GCC version
      run: gcc --version
    - name: Check G++ version
      run: g++ --version
    - name: Export compilers
      run: |
        export CC=gcc-9
        export CXX=g++-9
    - name: Configure the project
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: Build the project
      run: |
        cd build
        make -j$(nproc) VERBOSE=1